### ISSUE TITLE
Support non-UTF8 encodings

### ISSUE THREAD

**Issue by jsonn** [jelmer/python-fastimport#11]
When using fastimport streams from sources other than git, it is sometimes handy to deal with non-UTF8 commit messages. [This patch from pkgsrc](https://raw.githubusercontent.com/NetBSD/pkgsrc/trunk/devel/py-fastimport/patches/patch-fastimport_parser.py) adds an option to provide a fallback encoding, i.e. latin1.

**Comment by jelmer** [comment]
This doesn't belong in python-fastimport; it just parses and provides bytestrings.

It's up to the user of the library to do the decoding, if it cares. This kind of logic (what encoding to try first, etc) belongs there.
